--- #YAML:1.0
name:               Net-SSH-AuthorizedKeysFile
version:            0.12
abstract:           Read and modify ssh's authorized_keys files
author:
    - Mike Schilli <m@perlmeister.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Copy:        0
    File::Temp:        0
    Log::Log4perl:     1
    Test::More:        0
    Text::ParseWords:  0
resources:
    repository:  http://github.com/mschilli/net-ssh-authorizedkeysfile-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
